/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Mar 22 2023
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

#define _XTAL_FREQ 4M   
#define delayLoop for(j=0;j<100;j++)

#pragma config FOSC = XT 
#pragma config WDTE = OFF 
#pragma config PWRTE = ON 
#pragma config BOREN = ON 
#pragma config LVP = OFF 
#pragma config CPD = OFF 
#pragma config WRT = OFF 
#pragma config CP = OFF

int j;
bit myINTF = 0;


void interrupt ISR()
{
   GIE = 0;
   if(INTF)
   {
      INTF = 0;
      myINTF ^= 1;
	  
   }
   GIE = 1;
}
char mapKeypadToCharacter(int read)
{
   switch (read){
      case 0x00:
	 return '1';
      case 0x01:
	 return '2';
      case 0x02:
	 return '3';
      case 0x04:
	 return '4';
      case 0x05:
	 return '5';
      case 0x06:
	 return '6';
      case 0x08:
	 return '7';
      case 0x09:
	 return '8';
      case 0x0A:
	 return '9';
      case 0x0C:
	 return '*';
      case 0x0D:
	 return '0';
      case 0x0E:
	 return '#';
      default:
	 break;
   }
   return 'X';
}
void displayToTerminal(const unsigned char *s)
{
   int read;
    while(*s) {
       while(!TRMT);
       TXREG = *s++;
    }
    read = PORTB >> 4 & (0x0F);
    TXREG = mapKeypadToCharacter(read);
    while(RB0); // debounce sinas
    TXREG = '.';
    TXREG = 0x0D; //carriage return / newline
}

void main(void) 
{ 
   GIE = 1;
   ADCON1 = 0x06;
   CMCON = 0x07;
   OPTION_REG = 0x40;
   INTE = 1;
   INTF = 0;
   PEIE = 1;
   TRISB = 0xFF;
   TRISD = 0x00;
   
   //USART -------------
    SPBRG = 0x19; // 9.6K baud rate @ FOSC=4MHz, asynchronous high speed 
    // (see formula in Table 10-1) 
    SYNC = 0; // asynchronous mode (TXSTA reg) 
    SPEN = 1; // enable serial port (RCSTA reg) 
    TX9 = 0; // 8-bit transmission (TXSTA reg) 
    BRGH = 1; // asynchronous high-speed (TXSTA reg) 
    TXEN = 1; // transmit enable (TXSTA reg)
   SREN = 1; 
   PORTD = 0x00;
    for(;;) // foreground routine 
    { 
       while(!TRMT);
	if(myINTF)
	   displayToTerminal("You pressed ");
	myINTF = 0;
	delayLoop;
	
    } 
}