/* Main.c file generated by New Project wizard
 *
 * Created:   Fri Apr 3 2026
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

#define _XTAL_FREQ 4000000UL

#pragma config FOSC = XT
#pragma config WDTE = OFF
#pragma config PWRTE = ON
#pragma config BOREN = ON
#pragma config LVP = OFF
#pragma config CPD = OFF
#pragma config WRT = OFF
#pragma config CP = OFF

#define RS RD0
#define RW RD1
#define EN RD2


// Global volatile variable (32-bit to prevent overflow at low frequencies)
volatile unsigned long period = 0;

void instCtrl(unsigned char data) //take data input from initLCD
{
    PORTB= data;
    RS=0;
    RW=0;
    EN=1; //strobe
    __delay_us(50);;
    EN=0;
}

void initLCD()
{
    __delay_ms(20);    
   instCtrl(0x38); // 8-bit, 2 lines, 5x7 dots
   instCtrl(0x0C); // Display ON, cursor OFF, blink OFF
   instCtrl(0x01); // Clear display
   __delay_ms(2);  // Clear needs longer delay
   instCtrl(0x06); // Entry mode set (increment, no shift)
   instCtrl(0x80); // Cursor home
}

void dataCtrl(unsigned char b)
{
    PORTB=b; //write mode
    RS=1; //data signal
    RW=0; //write mode
    EN=1; //strobe high
    __delay_us(50);;
    EN=0; //strobe low
}

void printString(const char* str) {
    // Loop through the string array until it hits the null terminator
    while(*str) {
        dataCtrl(*str++);
    }
}

// Custom function to convert a 32-bit integer to string and print it
void printNumber(unsigned long val) {
    char buffer[11]; // Max 32-bit unsigned int is 4,294,967,295 (10 digits) + null
    buffer[10] = '\0';
    int i = 9;
    
    if (val == 0) {
        buffer[i--] = '0';
    } 
    else {
        // Extract digits right-to-left
        while (val > 0 && i >= 0) {
            buffer[i--] = (val % 10) + '0'; // Convert math digit to ASCII character
            val /= 10;
        }
    }
    // Print the string starting from the first valid character we wrote
    printString(&buffer[i + 1]);
}


void interrupt ISR(void) 
{  
   GIE = 0;          	// disable all unmasked interrupts (INTCON reg)            
   if(CCP1IF==1)     	// checks CCP1 interrupt flag 
   { 
      CCP1IF = 0;	// clears interrupt flag 
      TMR1 = 0;          // resets TMR1 
      
      RA0^=1;
      period = (unsigned long)CCPR1 * 8;
   } 
   GIE = 1;		// enable all unmasked interrupts (INTCON reg)              
} 

void main(void) 
{ 
   ADCON1 = 0x07;
   PORTB = 0x00;
   PORTD = 0x00;
   
   TRISA = 0x00;
   TRISB = 0x00;
   TRISC = 0x04; 	// set RC2 to input 
   TRISD = 0x00;
   
   RA0 = 0;
   
   initLCD(); 
   
   T1CON = 0x30;     // 1:8 prescaler, Timer1 off 
   CCP1CON = 0x05;    // capture mode: every rising edge 
   CCP1IE = 1;       // enable TMR1/CCP1 match interrupt (PIE1 reg) 
   CCP1IF = 0;       // reset interrupt flag (PIR1 reg) 
   PEIE = 1;         // enable all peripheral interrupt (INTCON reg) 
   GIE = 1;          // enable all unmasked interrupts (INTCON reg)
   
   TMR1ON = 1;       // Turns on Timer1 (T1CON reg) 
  for(;;)  
  { 
     //instCtrl(0x80); // Move LCD cursor to Home (Line 1, Position 1)
     instCtrl(0xC6);
     printString("Period: ");
    
     instCtrl(0x9A);
     printNumber(period);
     printString(" us    "); // Extra spaces overwrite old characters if the number shrinks
     
     __delay_us(50); // Update the LCD periodically to prevent flickering
  } 
}